name: NDK build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - "master"
      - "dev/*"
      - "feat/*"
      - "fix/*"
    paths-ignore:
      - "**.yml"
      - "!.github/workflows/build-ndk.yml"
      - "**.json"
      - "!qpm.json"
      - "!mod.template.json"
      - "**.txt"
      - "!CMakeLists.txt"
      - "**.ps1"
      - "!build.ps1"
      - "!createqmod.ps1"
      - "**.md"
      - ".gitignore"
  pull_request:
    branches: master

jobs:
  qpm_info:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.read_qpm_info.outputs.name }}
      id: ${{ steps.read_qpm_info.outputs.id }}
      override_so_name: ${{ steps.read_qpm_info.outputs.override_so_name }}
      qmod_output_path: ${{ steps.read_qpm_info.outputs.qmod_output_path }}
      qmod_output_name: ${{ steps.read_qpm_info.outputs.qmod_output_name }}
      ndk: ${{ steps.read_qpm_info.outputs.ndk }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read info from qpm.json
        id: read_qpm_info
        run: |
          NAME="$(jq -r '.info.name' qpm.json)"
          ID="$(jq -r '.info.id' qpm.json)"
          OVERRIDE_SO_NAME="$(jq -r '.info.additionalData.overrideSoName' qpm.json)"
          QMOD_OUTPUT_PATH="$(jq -r '.workspace.qmodOutput' qpm.json)"
          NDK="$(jq -r '.workspace.ndk' qpm.json)"

          echo "name=${NAME}" | tee -a "$GITHUB_OUTPUT"
          echo "id=${ID}" | tee -a "$GITHUB_OUTPUT"
          echo "override_so_name=${OVERRIDE_SO_NAME}" | tee -a "$GITHUB_OUTPUT"
          echo "qmod_output_path=${QMOD_OUTPUT_PATH}" | tee -a "$GITHUB_OUTPUT"
          echo "qmod_output_name=$(basename "${QMOD_OUTPUT_PATH}")" | tee -a "$GITHUB_OUTPUT"
          echo "ndk=${NDK}" | tee -a "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: qpm_info
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: true
          lfs: true
          fetch-depth: 0
          fetch-tags: true

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Get home path
        run: |
          echo "HOME=$HOME" | tee -a "$GITHUB_ENV"

      - name: Extract version
        if: startsWith(github.ref, 'refs/tags/v') != ''
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          FULL_VERSION="${GITHUB_REF#refs/tags/v}"
          VERSION="${FULL_VERSION%%[-+]*}"

          echo "TAG=$TAG" | tee -a "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" | tee -a "$GITHUB_OUTPUT"
          echo "FULL_VERSION=$FULL_VERSION" | tee -a "$GITHUB_OUTPUT"

      - name: Update version in qpm.json, qpm.shared.json, and mod.template.json
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Update qpm.json
          if [ -f qpm.json ]; then
            MODIFIED_JSON="$(jq --arg version "$VERSION" '.info.version = $version' qpm.json)"
            echo "$MODIFIED_JSON" > qpm.json
          fi

          # Update qpm.shared.json if it exists
          if [ -f qpm.shared.json ]; then
            MODIFIED_JSON="$(jq --arg version "$VERSION" '.config.info.version = $version' qpm.shared.json)"
            echo "$MODIFIED_JSON" > qpm.shared.json
          fi

          # Update mod.template.json if it exists
          if [ -f mod.template.json ]; then
            MODIFIED_JSON="$(jq --arg version "$FULL_VERSION" '.version = $version' mod.template.json)"
            echo "$MODIFIED_JSON" > mod.template.json
          fi
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          FULL_VERSION: ${{ steps.version.outputs.FULL_VERSION }}

      # if we don't have a tag, don't do anything special
      - name: Setup qpm
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: Fernthedev/qpm-action@v1
        with:
          cache: true
          resolve_ndk: true
          restore: true
          workflow_token: ${{ github.token }}

      # if we have a tag, we are making a qpm release
      - name: Setup qpm for release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: Fernthedev/qpm-action@v1
        with:
          cache: true
          publish_token: ${{ secrets.QPM_TOKEN }}
          publish: late
          qpm_debug_bin: true
          qpm_qmod: ${{ needs.qpm_info.outputs.qmod_output_name }}
          qpm_release_bin: true
          resolve_ndk: true
          restore: true
          tag: ${{ steps.version.outputs.TAG }}
          version: ${{ steps.version.outputs.VERSION }}
          workflow_token: ${{ github.token }}

      - name: Build & Create Qmod
        run: |
          qpm s qmod
        env:
          GITHUB_WORKFLOW_RUN: "true"

      - name: Rename build artifacts
        run: |
          mv "./build/debug/${{ needs.qpm_info.outputs.override_so_name }}" "./build/debug_${{ needs.qpm_info.outputs.override_so_name }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          if-no-files-found: error
          path: |
            ./build/${{ needs.qpm_info.outputs.override_so_name }}
            ./build/debug_${{ needs.qpm_info.outputs.override_so_name }}
            ${{ needs.qpm_info.outputs.qmod_output_path }}

      # Upload the release assets
      - name: Get Library Name and Build ID
        if: startsWith(github.ref, 'refs/tags/v')
        id: lib_info
        run: |
          cd build
          echo "LIBNAME=$(basename "${{ needs.qpm_info.outputs.override_so_name }}")" | tee -a $GITHUB_OUTPUT
          echo "BUILD_ID=$(readelf -n "debug_$(basename "${{ needs.qpm_info.outputs.override_so_name }}")" | grep -Po "(?<=Build ID: )[0-9a-f]+")" | tee -a $GITHUB_OUTPUT

      - name: Calculate SHA-256 of the qmod file
        if: startsWith(github.ref, 'refs/tags/v')
        id: qmodsha
        run: |
          echo "QMOD_SHA=$(sha256sum "build/$(basename "${{ needs.qpm_info.outputs.qmod_output_path }}")" | grep -Po "^[0-9a-f]+")" | tee -a $GITHUB_OUTPUT

      - name: Upload .qmod
        if: startsWith(github.ref, 'refs/tags/v')
        id: upload_file_qmod
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          files: |
            ./*.qmod
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate release body
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          BODY_FILE="body.txt"
          echo '---' >> body.txt
          echo '' >> body.txt
          echo '### Build Information' >> body.txt
          echo '' >> body.txt
          echo "**Build ID:** ${{ steps.lib_info.outputs.BUILD_ID }}" >> body.txt
          echo '' >> body.txt
          echo '### Checksums' >> body.txt
          echo '' >> body.txt
          echo '```' >> body.txt
          sha256sum *.qmod >> body.txt
          (cd build && sha256sum *.so) >> body.txt
          echo '```' >> body.txt

      - name: Upload .so artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        id: upload_file_so
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            ./build/${{ needs.qpm_info.outputs.override_so_name }}
            ./build/debug_${{ needs.qpm_info.outputs.override_so_name }}
          body_path: body.txt
          generate_release_notes: true
